require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/migrate/**/*
    - db/schema.rb
    - test/**/*
    - tmp/**/*
    - views/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
    - Guardfile
    - config/environments/*

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150
