require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - db/migrate/**/*
    - db/schema.rb
    - test/**/*
    - tmp/**/*
    - views/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb
    - Guardfile
    - config/environments/*
    - config/initializers/rails_admin.rb

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 140

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Rails/ActiveRecordAliases:
  Exclude:
    - 'spec/**/*'

Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/will_paginate_helper.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/will_paginate_helper.rb

Rails/UniqueValidationWithoutIndex:
  Enabled:
    false

RSpec/ExampleLength:
  Exclude:
    - spec/services/proforma_service/convert_task_to_exercise_spec.rb
    - spec/services/proforma_service/convert_task_to_proforma_task_spec.rb

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 14

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/models/file_type_spec.rb

Style/Documentation:
  Enabled: false
