development:
  adapter: postgresql

test:
  adapter: test

production:
  adapter: postgresql # redis
  # all other options below are only used for redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: codeharbor_production
