codeocean:
  url: http://localhost
omniauth:
  mocksaml:
    enable: false
  bird:
    enable: false
    certificate: ~
    private_key: ~
  nbp:
    enable: false
    certificate: ~
    private_key: ~
oai_pmh:
  admin_mail: admin@example.org
nbp:
  push_connector:
    enable: true
    client_id: testing_client_id
    client_secret: testing_client_secret
    token_path: 'https://test.provider/token'
    api_host: 'https://test.api.host'
    source:
      organization: test_organization
      name: CodeHarbor
      slug: CoHaP2
