require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CollectionsController, type: :controller do


  before { allow_any_instance_of(CanCan::ControllerResource).to receive(:load_and_authorize_resource){ nil } }

  let(:valid_attributes) {
    FactoryBot.attributes_for(:collection)
  }

  let(:invalid_attributes) {
    {title: ''}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollectionsController. Be sure to keep this updated too.
  let(:valid_session) {
    {user_id: FactoryBot.create(:user).id}
  }

  describe "GET #index" do
    xit "assigns all collections as @collections" do
      collection = Collection.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:collections)).to eq([collection])
    end
  end

  describe "GET #show" do
    it "assigns the requested collection as @collection" do
      collection = Collection.create! valid_attributes
      get :show, params: {:id => collection.to_param}, session: valid_session
      expect(assigns(:collection)).to eq(collection)
    end
  end

  describe "GET #new" do
    it "assigns a new collection as @collection" do
      get :new, params: {}, session: valid_session
      expect(assigns(:collection)).to be_a_new(Collection)
    end
  end

  describe "GET #edit" do
    it "assigns the requested collection as @collection" do
      collection = Collection.create! valid_attributes
      get :edit, params: {:id => collection.to_param}, session: valid_session
      expect(assigns(:collection)).to eq(collection)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Collection" do
        expect {
          post :create, params: {:collection => valid_attributes}, session: valid_session
        }.to change(Collection, :count).by(1)
      end

      it "assigns a newly created collection as @collection" do
        post :create, params: {:collection => valid_attributes}, session: valid_session
        expect(assigns(:collection)).to be_a(Collection)
        expect(assigns(:collection)).to be_persisted
      end

      it "redirects to the created collection" do
        post :create, params: {:collection => valid_attributes}, session: valid_session
        expect(response).to redirect_to(collections_path)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved collection as @collection" do
        post :create, params: {:collection => invalid_attributes}, session: valid_session
        expect(assigns(:collection)).to be_a_new(Collection)
      end

      it "re-renders the 'new' template" do
        post :create, params: {:collection => invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested collection" do
        collection = Collection.create! valid_attributes
        put :update, params: {:id => collection.to_param, :collection => new_attributes}, session: valid_session
        collection.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested collection as @collection" do
        collection = Collection.create! valid_attributes
        put :update, params: {:id => collection.to_param, :collection => valid_attributes}, session: valid_session
        expect(assigns(:collection)).to eq(collection)
      end

      it "redirects to the collection" do
        collection = Collection.create! valid_attributes
        put :update, params: {:id => collection.to_param, :collection => valid_attributes}, session: valid_session
        expect(response).to redirect_to(collections_path)
      end
    end

    context "with invalid params" do
      it "assigns the collection as @collection" do
        collection = Collection.create! valid_attributes
        put :update, params: {:id => collection.to_param, :collection => invalid_attributes}, session: valid_session
        expect(assigns(:collection)).to eq(collection)
      end

      it "re-renders the 'edit' template" do
        collection = Collection.create! valid_attributes
        put :update, params: {:id => collection.to_param, :collection => invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested collection" do
      collection = Collection.create! valid_attributes
      expect {
        delete :destroy, params: {:id => collection.to_param}, session: valid_session
      }.to change(Collection, :count).by(-1)
    end

    it "redirects to the collections list" do
      collection = Collection.create! valid_attributes
      delete :destroy, params: {:id => collection.to_param}, session: valid_session
      expect(response).to redirect_to(collections_url)
    end
  end

end
