# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExecutionEnvironmentsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # ExecutionEnvironment. As you add validations to ExecutionEnvironment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExecutionEnvironmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all execution_environments as @execution_environments' do
      execution_environment = ExecutionEnvironment.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:execution_environments)).to eq([execution_environment])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested execution_environment as @execution_environment' do
      execution_environment = ExecutionEnvironment.create! valid_attributes
      get :show, params: {id: execution_environment.to_param}, session: valid_session
      expect(assigns(:execution_environment)).to eq(execution_environment)
    end
  end

  describe 'GET #new' do
    it 'assigns a new execution_environment as @execution_environment' do
      get :new, params: {}, session: valid_session
      expect(assigns(:execution_environment)).to be_a_new(ExecutionEnvironment)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested execution_environment as @execution_environment' do
      execution_environment = ExecutionEnvironment.create! valid_attributes
      get :edit, params: {id: execution_environment.to_param}, session: valid_session
      expect(assigns(:execution_environment)).to eq(execution_environment)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new ExecutionEnvironment' do
        expect do
          post :create, params: {execution_environment: valid_attributes}, session: valid_session
        end.to change(ExecutionEnvironment, :count).by(1)
      end

      it 'assigns a newly created execution_environment as @execution_environment' do
        post :create, params: {execution_environment: valid_attributes}, session: valid_session
        expect(assigns(:execution_environment)).to be_a(ExecutionEnvironment)
        expect(assigns(:execution_environment)).to be_persisted
      end

      it 'redirects to the created execution_environment' do
        post :create, params: {execution_environment: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ExecutionEnvironment.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved execution_environment as @execution_environment' do
        post :create, params: {execution_environment: invalid_attributes}, session: valid_session
        expect(assigns(:execution_environment)).to be_a_new(ExecutionEnvironment)
      end

      it "re-renders the 'new' template" do
        post :create, params: {execution_environment: invalid_attributes}, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested execution_environment' do
        execution_environment = ExecutionEnvironment.create! valid_attributes
        put :update, params: {id: execution_environment.to_param, execution_environment: new_attributes}, session: valid_session
        execution_environment.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested execution_environment as @execution_environment' do
        execution_environment = ExecutionEnvironment.create! valid_attributes
        put :update, params: {id: execution_environment.to_param, execution_environment: valid_attributes}, session: valid_session
        expect(assigns(:execution_environment)).to eq(execution_environment)
      end

      it 'redirects to the execution_environment' do
        execution_environment = ExecutionEnvironment.create! valid_attributes
        put :update, params: {id: execution_environment.to_param, execution_environment: valid_attributes}, session: valid_session
        expect(response).to redirect_to(execution_environment)
      end
    end

    context 'with invalid params' do
      it 'assigns the execution_environment as @execution_environment' do
        execution_environment = ExecutionEnvironment.create! valid_attributes
        put :update, params: {id: execution_environment.to_param, execution_environment: invalid_attributes}, session: valid_session
        expect(assigns(:execution_environment)).to eq(execution_environment)
      end

      it "re-renders the 'edit' template" do
        execution_environment = ExecutionEnvironment.create! valid_attributes
        put :update, params: {id: execution_environment.to_param, execution_environment: invalid_attributes}, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested execution_environment' do
      execution_environment = ExecutionEnvironment.create! valid_attributes
      expect do
        delete :destroy, params: {id: execution_environment.to_param}, session: valid_session
      end.to change(ExecutionEnvironment, :count).by(-1)
    end

    it 'redirects to the execution_environments list' do
      execution_environment = ExecutionEnvironment.create! valid_attributes
      delete :destroy, params: {id: execution_environment.to_param}, session: valid_session
      expect(response).to redirect_to(execution_environments_url)
    end
  end
end
