# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LicensesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # License. As you add validations to License, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LicensesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all licenses as @licenses' do
      license = License.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:licenses)).to eq([license])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested license as @license' do
      license = License.create! valid_attributes
      get :show, params: {id: license.to_param}, session: valid_session
      expect(assigns(:license)).to eq(license)
    end
  end

  describe 'GET #new' do
    it 'assigns a new license as @license' do
      get :new, params: {}, session: valid_session
      expect(assigns(:license)).to be_a_new(License)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested license as @license' do
      license = License.create! valid_attributes
      get :edit, params: {id: license.to_param}, session: valid_session
      expect(assigns(:license)).to eq(license)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new License' do
        expect do
          post :create, params: {license: valid_attributes}, session: valid_session
        end.to change(License, :count).by(1)
      end

      it 'assigns a newly created license as @license' do
        post :create, params: {license: valid_attributes}, session: valid_session
        expect(assigns(:license)).to be_a(License)
      end

      it 'persists @license' do
        post :create, params: {license: valid_attributes}, session: valid_session
        expect(assigns(:license)).to be_persisted
      end

      it 'redirects to the created license' do
        post :create, params: {license: valid_attributes}, session: valid_session
        expect(response).to redirect_to(License.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved license as @license' do
        post :create, params: {license: invalid_attributes}, session: valid_session
        expect(assigns(:license)).to be_a_new(License)
      end

      it "re-renders the 'new' template" do
        post :create, params: {license: invalid_attributes}, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested license' do
        license = License.create! valid_attributes
        put :update, params: {id: license.to_param, license: new_attributes}, session: valid_session
        license.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested license as @license' do
        license = License.create! valid_attributes
        put :update, params: {id: license.to_param, license: valid_attributes}, session: valid_session
        expect(assigns(:license)).to eq(license)
      end

      it 'redirects to the license' do
        license = License.create! valid_attributes
        put :update, params: {id: license.to_param, license: valid_attributes}, session: valid_session
        expect(response).to redirect_to(license)
      end
    end

    context 'with invalid params' do
      it 'assigns the license as @license' do
        license = License.create! valid_attributes
        put :update, params: {id: license.to_param, license: invalid_attributes}, session: valid_session
        expect(assigns(:license)).to eq(license)
      end

      it "re-renders the 'edit' template" do
        license = License.create! valid_attributes
        put :update, params: {id: license.to_param, license: invalid_attributes}, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested license' do
      license = License.create! valid_attributes
      expect do
        delete :destroy, params: {id: license.to_param}, session: valid_session
      end.to change(License, :count).by(-1)
    end

    it 'redirects to the licenses list' do
      license = License.create! valid_attributes
      delete :destroy, params: {id: license.to_param}, session: valid_session
      expect(response).to redirect_to(licenses_url)
    end
  end
end
